#define TILE_SIZE               30
#define FRAMERATE_LIMIT         10
#define HEIGHT_TOP_PANEL        3
#define EASY_X                  10
#define EASY_Y                  10
#define EASY_BOMBS_RATIO        0.16
#define MEDIUM_X                15
#define MEDIUM_Y                15
#define MEDIUM_BOMBS_RATIO      0.18
#define HARD_X                  25
#define HARD_Y                  20
#define HARD_BOMBS_RATIO        0.22


#define TITLE                           "Minesweeper!"
#define TILES_FILEPATH                  "resources/images/tiles.jpg"
#define HEAD_GAME_FILEPATH              "resources/images/youPlay.jpg"
#define HEAD_WON_FILEPATH               "resources/images/youWon.jpg"
#define HEAD_LOST_FILEPATH              "resources/images/youLost.jpg"
#define TEXT_BACKGROUND_FILEPATH        "resources/images/numBckg.jpg" 
#define OK_BUTTON_FILEPATH              "resources/images/ok.jpg" 
#define LOGO_FILEPATH                   "resources/images/logo.jpg" 
#define CALCULATOR_FONT_FILEPATH        "resources/fonts/calcFont.otf"
#define BEST_SCORE_FONT_FILEPATH        "resources/fonts/arial.ttf"
#define BEST_SCORE_EASY_LIST_FILEPATH   "resources/highscoreEasy.txt"
#define BEST_SCORE_MEDIUM_LIST_FILEPATH "resources/highscoreMedium.txt"
#define BEST_SCORE_HARD_LIST_FILEPATH   "resources/highscoreHard.txt"
#define EASY_BUTTON_FILEPATH            "resources/images/buttons_start/easy.jpg"
#define MEDIUM_BUTTON_FILEPATH          "resources/images/buttons_start/medium.jpg"
#define HARD_BUTTON_FILEPATH            "resources/images/buttons_start/hard.jpg"
